"""
extract_contrib.py

For every document in documents.json (using meta.json for client / shortcode):

  1. Finds the document XML inside its folder (e.g. JATS/<docid>/)
  2. Extracts the <contrib-group> XML        -> <folder>/contrib_group.xml
  3. Builds an HTML preview of all contribs   -> <folder>/contrib_preview.html
  4. Builds TWO reports per client + shortcode under
     Documents/impact-support-log/{YYYYMMDD_HHMMSS}_contrib_reports/JATS/:
     (meta-contrib.json stays at <root>; per-doc xml/html stay in each doc folder)
       <client>_<shortcode>_contrib_v<N>.html   PI value + PI position only
       <client>_<shortcode>_elements_v<N>.html  elements + flags only
       <client>_<shortcode>_issues_v<N>.csv     the findings of the contrib report (with contrib_group, contribs)

Version
-------
  SCRIPT_VERSION (top of the file) is bumped on every script change. It is in
  the file names (_v9), shown as a header chip and stored in meta-contrib.json:
  a shortcode generated by an older version shows as [update] and is
  regenerated on the next run. Older versioned files stay on disk.
      v1  contrib-group extraction, HTML preview (pistart text restored), report per shortcode
      v2  Raw XML toggle, Docid column, sticky header, all-contrib consistency check
      v3  pattern statistics, JATS-only run + meta-contrib.json + pauses,
          1/2/3+ column rule, xref groups
      v4  versioned file names, element inventory
      v5  (element list hid the default elements - withdrawn)
      v6  element list shows ALL elements again
      v7  (element chips inside the contrib report - withdrawn)
      v8  two clearly separated reports; xref groups 0/1/2/3+ with first /
          last-before / last xref roles; files-to-fix table, pattern previews,
          issues.csv, "only files with issues" filter; element flags
      v9  contrib report in tabs (1 contrib | 2 contribs | 3+ contribs | Failed):
          statistics, files to fix, PI check and file table per tab, only the
          columns that tab has; PI attr / PI position toggle, xref chips,
          cross-group check, search box, copy-IDs buttons, sample previews
          (shortest first, "next sample"), small-group marker, URL state,
          contrib_group + contribs columns in issues.csv

1. CONTRIB REPORT  (PI attr value + PI position, nothing else)
--------------------------------------------------------------
  Columns: File ID | Docid | First contrib | Last before | Last contrib
  (each tab shows only the columns it has)
  Which contrib goes in which column (by the number of contribs):
      1 contrib    -> Last contrib only            (First, Last before = "-")
      2 contribs   -> Last before + Last contrib   (First = "-")
      3+ contribs  -> First, Last before (2nd from the end), Last contrib

  Layout (top to bottom)
    Cross-group check   is pattern-1 the same in the 1 / 2 / 3+ tabs? (a tab
                        link is given where it differs)
    Tab bar             1 contrib | 2 contribs | 3+ contribs | Failed - file
                        count and warning count per tab; search box and
                        "only files with issues" filter apply to every tab
    Inside a tab        Files to fix   one row per off-pattern file (copy-IDs button)
                        Statistics     PI attr value / PI position / both (toggle),
                                       xref chips (All, 0, 1, 2, 3+); only this tab's
                                       columns; pattern-N and % are relative to the tab;
                                       each pattern has sample previews (shortest first,
                                       "next sample") with the differing pistarts in red
                        PI check on all contribs   same "same value, same position"
                                       idea, expected values taken over ALL files
                        File table     preview (pistart text restored) or Raw XML
                                       (toggle in the header), pattern-N tags
  Tabs: the URL hash keeps the state (#tab=g3&kind=attr, #row-<docid> opens the
  right tab and scrolls to the file). Without JavaScript every tab is shown.
  Groups with fewer than SMALL_GROUP files are marked "small group".

  xref groups: files are split by the number of <xref> in the contrib:
      xref 0 | xref 1 | xref 2 | xref 3+
  and only three xrefs are looked at, named by role like the contribs:
      1 xref  -> last            2 xrefs -> last-before, last
      3+ xrefs -> first, last-before, last   (middle xrefs are skipped)
  The pistart after an xref is written as "after first xref",
  "after last-before xref", "after last xref". The middle xrefs are only
  covered by the "PI check on all contribs".

  Patterns: every file is reduced to two patterns per column
      PI attr value : the ordered pistart values of that contrib
      PI position   : the ordered places where a pistart sits
  Inside each xref group the files get pattern-N  <files with it>/<files in
  the group>; pattern-1 is the most common. Other patterns list their files
  and say what differs: differs / missing / extra.

  Preview rule: <?pistart xml:space=",&#x00A0;"?> -> the attribute value is put
  back as real text at that position. Other PIs and comments are ignored.

  PI check on all contribs: a "position" is a gap inside a <contrib>. The
  value of a position is the pistart text sitting there. Contribs are only
  compared with contribs of the same class (last / last before / other) and
  the same xref group; where a position has more than one value, the most
  common one is expected and the others are flagged (red = different,
  warning = missing). Middle xrefs are compared here too.

2. ELEMENT LIST  (elements + flags, no pistart values)
------------------------------------------------------
  Every element name found in the <contrib-group>s of the shortcode, nothing
  excluded: files containing it, occurrences, per-contrib counts
  (e.g. xref 0: 12 . 1: 340 . 2: 210), parents, attributes (values + counts).
  Flags: partial (not in every file - the files are listed), rare (in
  RARE_MAX files or fewer), repeats (more than one per contrib), empty (no text
  and no child element, e.g. an <email> that only holds a PI), rare attribute
  values. Other processing instructions (attributepistart, PageID ...) and
  comments are listed as flags only (files + occurrences, no values).

Selection + meta-contrib.json
-----------------------------
  Only documents whose meta.json "dtd" is JATS are used (RUN_DTD below; BITS
  is ignored). Before anything runs an overview lists Clients -> Shortcodes
  with doc counts and whether each is already filled (generated) or not.
  You are then asked for the client(s) and the shortcode(s):
      Enter  = every shortcode that is not filled or has new docs   (default)
      1,3    = the numbers / names you type (asks before redoing a filled one)
      all    = regenerate everything for the chosen client(s)

  Every generated shortcode is recorded in root/meta-contrib.json so it is
  not generated again:

      { "JATS": { "LWW": { "INF": {
            "generated_at": "...", "version": 9,
            "report": "/.../Documents/impact-support-log/{ts}_contrib_reports/JATS/LWW_INF_contrib_v9.html",
            "elements_report": "...", "issues_csv": "...",
            "groups": { "g1": {"files": 12, "off_pattern": 0, "pi_issues": 0}, "g2": ..., "g3": ... },
            "cross_group_differences": 0,
            "documents": 45, "failed": 0, "off_pattern_files": 3,
            "consistency_issues": 4,
            "docids": { "<docid>": {"file-id": "...", "contribs": 18, "status": "ok"}, ... }
      } } } }

  Run order: strictly one shortcode at a time (reports written and recorded in
  meta-contrib.json), then a pause, then the next shortcode of that client.
  When a client is complete there is a (longer) pause and the next client
  starts. Pauses are asked once (Enter = defaults DELAY_SHORTCODE_SEC /
  DELAY_CLIENT_SEC). Ctrl+C stops cleanly; finished shortcodes stay recorded.
  A shortcode counts as "update" when meta.json has docids that are not
  recorded yet, or when it was generated by an older SCRIPT_VERSION.
  Regenerating a shortcode always rebuilds its whole report.

Expected layout:
    root/documents.json
    root/meta.json
    root/meta-contrib.json      (created / updated by this script)
    root/<folder from documents.json>/...xml
    ~/Documents/impact-support-log/{ts}_contrib_reports/JATS/   (HTML/CSV reports)

Usage:
    python extract_contrib.py
    (then enter the project root folder, client and shortcode when prompted)

Requires Python 3.10+. No extra packages.
"""

import csv
import difflib
import html
import json
import os
import re
import time
import traceback
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from html.entities import name2codepoint
from pathlib import Path

DOCS_NAME = "documents.json"
META_NAME = "meta.json"
DONE_NAME = "meta-contrib.json"   # what has already been generated
REPORT_DIR = "contrib_reports"   # suffix of timestamped folder: {ts}_contrib_reports
SUPPORT_LOG_NAME = "impact-support-log"
# Tests / callers may set REPORT_ROOT to redirect away from ~/Documents/...
REPORT_ROOT: Path | None = None
RUN_DTD = "JATS"                 # only this DTD is processed
SCRIPT_VERSION = 9               # bump on EVERY script change: goes into file names (_v9) and marks old reports as "update"
RARE_MAX = 2                     # element list: "rare" = in this many files or fewer
SMALL_GROUP = 5                  # contrib report: a group / xref group with fewer files is marked "small"
SAMPLES = 3                      # contrib report: sample previews per pattern (button cycles through them)
DELAY_SHORTCODE_SEC = 5          # default pause between two shortcodes of one client
DELAY_CLIENT_SEC = 10            # default pause when the next shortcode belongs to another client
OUT_XML = "contrib_group.xml"
OUT_HTML = "contrib_preview.html"

# xml files that must never be treated as the document xml
SKIP_XML = {"impact_config.xml", OUT_XML}

HIGHLIGHT_PI = True  # yellow background on text restored from pistart

CONTRIB_GROUP_RE = re.compile(r"<contrib-group\b.*?</contrib-group>", re.S)
CONTRIB_RE = re.compile(r"<contrib(?=[\s>]).*?</contrib>", re.S)
NAMED_ENTITY_RE = re.compile(r"&([A-Za-z][A-Za-z0-9]*);")
PI_VALUE_RE = re.compile(r"""xml:space\s*=\s*(?:"([^"]*)"|'([^']*)')""")
WS_RE = re.compile(r"[ \t\r\n]+")  # NOTE: does not match nbsp on purpose
XML_ENTITIES = {"amp", "lt", "gt", "quot", "apos"}

NS_DECLS = (
    'xmlns:xlink="http://www.w3.org/1999/xlink" '
    'xmlns:mml="http://www.w3.org/1998/Math/MathML" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
)

INLINE_TAGS = {"sup": "sup", "sub": "sub", "italic": "i", "bold": "b"}

PI = ET.ProcessingInstruction


